#!/bin/bash

#SBATCH --job-name=TE_Divergence_Plotting
#SBATCH --partition=pibu_el8
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=00:30:00
#SBATCH --output=./logs/output/%x_%j.out
#SBATCH --error=./logs/error/%x_%j.err

#==============================================================================
# SCRIPT: 04.2_wrapper_plot_divergence.sh
# DESCRIPTION: SLURM wrapper to execute the R script for plotting TE divergence
#              landscape based on the data binned in step 03.
#==============================================================================

#*-----Variables and File Setup------------------------------------------------*
WORKDIR="/data/users/aboss/annotation_of_eukaryote_genome"
# The R script that generates the plot (needs to be saved as a separate file)
R_SCRIPT="${WORKDIR}/scripts/04.3_plot_divergence.R"
# Directory containing the input data (from 03_bin_te_divergence.sh)
INPUT_DIR="${WORKDIR}/results/03_TE_Divergence_Binning"
# Output directory for the final plot
PLOT_OUTDIR="${WORKDIR}/results/03_TE_Divergence_Binning/Plots" 
# Name of the input data file generated by parseRM.pl. Check the exact name!
INPUT_DATA_FILE="hifiasm_assembly_Altai-5.fasta.mod.out.landscape.Div.Rname.tab"

#*-----Prerequisites and Directory Setup---------------------------------------*
echo "Loading required software modules..."
# BioPerl is not needed for R, but loading R and the CRAN bundle is critical
# R-bundle-CRAN usually contains ggplot2, reshape2, tidyverse etc.
module add R/4.3.2-foss-2021a
module add R-bundle-CRAN/2023.11-foss-2021a

mkdir -p "$PLOT_OUTDIR"

#*-----Run R Plotting Script---------------------------------------------------*
echo "Executing R plotting script: $R_SCRIPT"
# We pass the input file path and the output plot directory as arguments to the R script
Rscript "$R_SCRIPT" \
    "${INPUT_DIR}/${INPUT_DATA_FILE}" \
    "$PLOT_OUTDIR"

echo "R script finished. Results saved in $PLOT_OUTDIR"