#!/bin/bash
#SBATCH --job-name=AED_plot
#SBATCH --partition=pibu_el8
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=0-01:00:00
#SBATCH --output=logs/output/%x_%j.out
#SBATCH --error=logs/error/%x_%j.err

#*-----Variables and File Setup------------------------------------------------*
WORKDIR="/data/users/aboss/annotation_of_eukaryote_genome"
# The R script that generates the plot (needs to be saved as a separate file)
R_SCRIPT="${WORKDIR}/scripts/17.2_aed_plot.R"
# Directory containing the input data (from 03_bin_te_divergence.sh)
INPUT_DIR="${WORKDIR}/results/08_Maker/final"
# Output directory for the final plot
PLOT_OUTDIR="${WORKDIR}/results/08_Maker/final/Plots" 
# Name of the input data file generated by parseRM.pl. Check the exact name!
INPUT_DATA_FILE="assembly.all.maker.renamed.gff.AED.txt"

#*-----Prerequisites and Directory Setup---------------------------------------*
echo "Loading required software modules..."
# BioPerl is not needed for R, but loading R and the CRAN bundle is critical
# R-bundle-CRAN usually contains ggplot2, reshape2, tidyverse etc.
module add R/4.3.2-foss-2021a
module add R-bundle-CRAN/2023.11-foss-2021a

mkdir -p "$PLOT_OUTDIR"
cd "$WORKDIR" || exit 1


#*-----Run R Plotting Script---------------------------------------------------*
echo "Executing R plotting script: $R_SCRIPT"
# We pass the input file path and the output plot directory as arguments to the R script
Rscript "$R_SCRIPT" \
    "${INPUT_DIR}/${INPUT_DATA_FILE}" \
    "$PLOT_OUTDIR"


